#ifndef CML_ALL
#define CML_ALL

#include "CheckGrad.h"
#include "MyLib.h"
#include "Metric.h"
#include "NRMat.h"
#include "Alphabet.h"
#include "Hash_map.hpp"
#include "Utiltensor.h"
#include "Pooling.h"
#include "Dropout.h"
#include "Concat.h"
#include "Windowlized.h"
#include "LookupTable.h"
#include "GatedPooling.h"
#include "AttentionPooling.h"
#include "BiLayer.h"
#include "RNN.h"
#include "GRNN.h"
#include "LSTM.h"
#include "LSTM_STD.h"
#include "LSTM_KER.h"
#include "LSTM_CHD.h"
#include "SoftMaxLoss.h"
#include "MLCRFLoss.h"
#include "MMCRFLoss.h"
#include "RecursiveNN.h"
#include "RecursiveGatedNN.h"
#include "AttRecursiveGatedNN.h"
#include "SparseUniLayer.h"
#include "SparseUniLayer1O.h"
#include "TensorLayer.h"
#include "TriLayer.h"
#include "UniLayer.h"
#include "UniLayer1O.h"
#include "AvgPerceptron1O.h"
#include "IO.h"


#endif
